image: ruby:2.3.1

services:
  - postgres:9.5

variables:
   POSTGRES_DB: db_name
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres

cache:
  paths:
    - vendor/bundle

before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs libsqlite3-dev
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --deployment --path vendor/bundle --jobs $(nproc)  "${FLAGS[@]}"
tests:
  script:
    - RAILS_ENV=test bundle exec rake db:create db:migrate
    - RAILS_ENV=test bundle exec rake test

staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=test-app-kroosh --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
