image: ruby:2.3.1
before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs libsqlite3-dev
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --deployment --path vendor/bundle --jobs $(nproc)  "${FLAGS[@]}"
tests:
  script:
    - bundle exec rake test

staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=test-app-kroosh --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
