rvm:
  - 2.3.1

services:
  - postgres:9.5

before_script:
  - "cp .env.travis .env"
  - "bundle exec rake db:drop db:create db:migrate"

script: "RAILS_ENV=test bundle exec rake test"

deploy:
  provider: heroku
  api_key: $HEROKU_STAGING_API_KEY
  app: test-app-kroosh
